package personnages;

public class Gaulois {
	private String nom;
	private int force;
	private int effetPotion = 1;
	
	public Gaulois(String nom, int force) {//Generated by selecting fields to initialize in Source>Gnerated..Fields
		this.nom = nom;
		this.force = force;
	}
	//Generated by Source>Generate getters and setters
	// Ctrl / for commenting in mass
//	public int getForce() {
//		return force;
//	}
//
//	public void setForce(int force) {
//		this.force = force;
//	}
//
//	public int getEffetPotion() {
//		return effetPotion;
//	}
	

}
